<?php
declare(strict_types=1);

namespace Smetaniny\TailwindcssConfig\seeders;

use Illuminate\Support\Facades\DB;
use Smetaniny\TailwindcssConfig\Commands\Contracts\SeederInterface;

/**
 * Сидер для заполнения таблицы `tw_accent_colors` всеми возможными акцентными цветами.
 *
 * @author Smetanin Sergey
 */
class TwAccentColors implements SeederInterface
{
    /**
     * Выполняет вставку данных в таблицу акцентных цветов.
     */
    public function run(): void
    {
        // Проверяем, что таблица пуста
        if (DB::table('tw_accent_colors')->count() == 0) {
            DB::table('tw_accent_colors')->insert([
                [
                    ['name' => 'accent-inherit', 'hex_value' => 'inherit'],
                    ['name' => 'accent-current', 'hex_value' => 'currentColor'],
                    ['name' => 'accent-transparent', 'hex_value' => 'transparent'],
                    ['name' => 'accent-black', 'hex_value' => '#000'],
                    ['name' => 'accent-white', 'hex_value' => '#fff'],
                    ['name' => 'accent-slate-50', 'hex_value' => '#f8fafc'],
                    ['name' => 'accent-slate-100', 'hex_value' => '#f1f5f9'],
                    ['name' => 'accent-slate-200', 'hex_value' => '#e2e8f0'],
                    ['name' => 'accent-slate-300', 'hex_value' => '#cbd5e1'],
                    ['name' => 'accent-slate-400', 'hex_value' => '#94a3b8'],
                    ['name' => 'accent-slate-500', 'hex_value' => '#64748b'],
                    ['name' => 'accent-slate-600', 'hex_value' => '#475569'],
                    ['name' => 'accent-slate-700', 'hex_value' => '#334155'],
                    ['name' => 'accent-slate-800', 'hex_value' => '#1e293b'],
                    ['name' => 'accent-slate-900', 'hex_value' => '#0f172a'],
                    ['name' => 'accent-slate-950', 'hex_value' => '#020617'],
                    ['name' => 'accent-gray-50', 'hex_value' => '#f9fafb'],
                    ['name' => 'accent-gray-100', 'hex_value' => '#f3f4f6'],
                    ['name' => 'accent-gray-200', 'hex_value' => '#e5e7eb'],
                    ['name' => 'accent-gray-300', 'hex_value' => '#d1d5db'],
                    ['name' => 'accent-gray-400', 'hex_value' => '#9ca3af'],
                    ['name' => 'accent-gray-500', 'hex_value' => '#6b7280'],
                    ['name' => 'accent-gray-600', 'hex_value' => '#4b5563'],
                    ['name' => 'accent-gray-700', 'hex_value' => '#374151'],
                    ['name' => 'accent-gray-800', 'hex_value' => '#1f2937'],
                    ['name' => 'accent-gray-900', 'hex_value' => '#111827'],
                    ['name' => 'accent-gray-950', 'hex_value' => '#030712'],
                    ['name' => 'accent-zinc-50', 'hex_value' => '#fafafa'],
                    ['name' => 'accent-zinc-100', 'hex_value' => '#f4f4f5'],
                    ['name' => 'accent-zinc-200', 'hex_value' => '#e4e4e7'],
                    ['name' => 'accent-zinc-300', 'hex_value' => '#d4d4d8'],
                    ['name' => 'accent-zinc-400', 'hex_value' => '#a1a1aa'],
                    ['name' => 'accent-zinc-500', 'hex_value' => '#71717a'],
                    ['name' => 'accent-zinc-600', 'hex_value' => '#52525b'],
                    ['name' => 'accent-zinc-700', 'hex_value' => '#3f3f46'],
                    ['name' => 'accent-zinc-800', 'hex_value' => '#27272a'],
                    ['name' => 'accent-zinc-900', 'hex_value' => '#18181b'],
                    ['name' => 'accent-zinc-950', 'hex_value' => '#09090b'],
                    ['name' => 'accent-neutral-50', 'hex_value' => '#fafafa'],
                    ['name' => 'accent-neutral-100', 'hex_value' => '#f5f5f5'],
                    ['name' => 'accent-neutral-200', 'hex_value' => '#e5e5e5'],
                    ['name' => 'accent-neutral-300', 'hex_value' => '#d4d4d4'],
                    ['name' => 'accent-neutral-400', 'hex_value' => '#a3a3a3'],
                    ['name' => 'accent-neutral-500', 'hex_value' => '#737373'],
                    ['name' => 'accent-neutral-600', 'hex_value' => '#525252'],
                    ['name' => 'accent-neutral-700', 'hex_value' => '#404040'],
                    ['name' => 'accent-neutral-800', 'hex_value' => '#262626'],
                    ['name' => 'accent-neutral-900', 'hex_value' => '#171717'],
                    ['name' => 'accent-neutral-950', 'hex_value' => '#0a0a0a'],
                    ['name' => 'accent-stone-50', 'hex_value' => '#fafaf9'],
                    ['name' => 'accent-stone-100', 'hex_value' => '#f5f5f4'],
                    ['name' => 'accent-stone-200', 'hex_value' => '#e7e5e4'],
                    ['name' => 'accent-stone-300', 'hex_value' => '#d6d3d1'],
                    ['name' => 'accent-stone-400', 'hex_value' => '#a8a29e'],
                    ['name' => 'accent-stone-500', 'hex_value' => '#78716c'],
                    ['name' => 'accent-stone-600', 'hex_value' => '#57534e'],
                    ['name' => 'accent-stone-700', 'hex_value' => '#44403c'],
                    ['name' => 'accent-stone-800', 'hex_value' => '#292524'],
                    ['name' => 'accent-stone-900', 'hex_value' => '#1c1917'],
                    ['name' => 'accent-stone-950', 'hex_value' => '#0c0a09'],
                    ['name' => 'accent-red-50', 'hex_value' => '#fef2f2'],
                    ['name' => 'accent-red-100', 'hex_value' => '#fee2e2'],
                    ['name' => 'accent-red-200', 'hex_value' => '#fecaca'],
                    ['name' => 'accent-red-300', 'hex_value' => '#fca5a5'],
                    ['name' => 'accent-red-400', 'hex_value' => '#f87171'],
                    ['name' => 'accent-red-500', 'hex_value' => '#ef4444'],
                    ['name' => 'accent-red-600', 'hex_value' => '#dc2626'],
                    ['name' => 'accent-red-700', 'hex_value' => '#b91c1c'],
                    ['name' => 'accent-red-800', 'hex_value' => '#991b1b'],
                    ['name' => 'accent-red-900', 'hex_value' => '#7f1d1d'],
                    ['name' => 'accent-red-950', 'hex_value' => '#450a0a'],
                    ['name' => 'accent-orange-50', 'hex_value' => '#fff7ed'],
                    ['name' => 'accent-orange-100', 'hex_value' => '#ffedd5'],
                    ['name' => 'accent-orange-200', 'hex_value' => '#fed7aa'],
                    ['name' => 'accent-orange-300', 'hex_value' => '#fdba74'],
                    ['name' => 'accent-orange-400', 'hex_value' => '#fb923c'],
                    ['name' => 'accent-orange-500', 'hex_value' => '#f97316'],
                    ['name' => 'accent-orange-600', 'hex_value' => '#ea580c'],
                    ['name' => 'accent-orange-700', 'hex_value' => '#c2410c'],
                    ['name' => 'accent-orange-800', 'hex_value' => '#9a3412'],
                    ['name' => 'accent-orange-900', 'hex_value' => '#7c2d12'],
                    ['name' => 'accent-orange-950', 'hex_value' => '#431407'],
                    // Дополняем остальные акцентные цвета
                    ['name' => 'accent-amber-50', 'hex_value' => '#fffbeb'],
                    ['name' => 'accent-amber-100', 'hex_value' => '#fef3c7'],
                    ['name' => 'accent-amber-200', 'hex_value' => '#fde68a'],
                    ['name' => 'accent-amber-300', 'hex_value' => '#fcd34d'],
                    ['name' => 'accent-amber-400', 'hex_value' => '#fbbf24'],
                    ['name' => 'accent-amber-500', 'hex_value' => '#f59e0b'],
                    ['name' => 'accent-amber-600', 'hex_value' => '#d97706'],
                    ['name' => 'accent-amber-700', 'hex_value' => '#b45309'],
                    ['name' => 'accent-amber-800', 'hex_value' => '#92400e'],
                    ['name' => 'accent-amber-900', 'hex_value' => '#78350f'],
                    ['name' => 'accent-amber-950', 'hex_value' => '#451a03'],
                    ['name' => 'accent-yellow-50', 'hex_value' => '#fefce8'],
                    ['name' => 'accent-yellow-100', 'hex_value' => '#fef9c3'],
                    ['name' => 'accent-yellow-200', 'hex_value' => '#fef08a'],
                    ['name' => 'accent-yellow-300', 'hex_value' => '#fde047'],
                    ['name' => 'accent-yellow-400', 'hex_value' => '#facc15'],
                    ['name' => 'accent-yellow-500', 'hex_value' => '#eab308'],
                    ['name' => 'accent-yellow-600', 'hex_value' => '#ca8a04'],
                    ['name' => 'accent-yellow-700', 'hex_value' => '#a16207'],
                    ['name' => 'accent-yellow-800', 'hex_value' => '#854d0e'],
                    ['name' => 'accent-yellow-900', 'hex_value' => '#713f12'],
                    ['name' => 'accent-yellow-950', 'hex_value' => '#422006'],
                    ['name' => 'accent-lime-50', 'hex_value' => '#f7fee7'],
                    ['name' => 'accent-lime-100', 'hex_value' => '#ecfccb'],
                    ['name' => 'accent-lime-200', 'hex_value' => '#d9f99d'],
                    ['name' => 'accent-lime-300', 'hex_value' => '#bef264'],
                    ['name' => 'accent-lime-400', 'hex_value' => '#a3e635'],
                    ['name' => 'accent-lime-500', 'hex_value' => '#84cc16'],
                    ['name' => 'accent-lime-600', 'hex_value' => '#65a30d'],
                    ['name' => 'accent-lime-700', 'hex_value' => '#4d7c0f'],
                    ['name' => 'accent-lime-800', 'hex_value' => '#3f6212'],
                    ['name' => 'accent-lime-900', 'hex_value' => '#365314'],
                    ['name' => 'accent-lime-950', 'hex_value' => '#1a2e05'],
                    ['name' => 'accent-green-50', 'hex_value' => '#f0fdf4'],
                    ['name' => 'accent-green-100', 'hex_value' => '#dcfce7'],
                    ['name' => 'accent-green-200', 'hex_value' => '#bbf7d0'],
                    ['name' => 'accent-green-300', 'hex_value' => '#86efac'],
                    ['name' => 'accent-green-400', 'hex_value' => '#4ade80'],
                    ['name' => 'accent-green-500', 'hex_value' => '#22c55e'],
                    ['name' => 'accent-green-600', 'hex_value' => '#16a34a'],
                    ['name' => 'accent-green-700', 'hex_value' => '#15803d'],
                    ['name' => 'accent-green-800', 'hex_value' => '#166534'],
                    ['name' => 'accent-green-900', 'hex_value' => '#14532d'],
                    ['name' => 'accent-green-950', 'hex_value' => '#052e16'],
                    ['name' => 'accent-emerald-50', 'hex_value' => '#ecfdf5'],
                    ['name' => 'accent-emerald-100', 'hex_value' => '#d1fae5'],
                    ['name' => 'accent-emerald-200', 'hex_value' => '#a7f3d0'],
                    ['name' => 'accent-emerald-300', 'hex_value' => '#6ee7b7'],
                    ['name' => 'accent-emerald-400', 'hex_value' => '#34d399'],
                    ['name' => 'accent-emerald-500', 'hex_value' => '#10b981'],
                    ['name' => 'accent-emerald-600', 'hex_value' => '#059669'],
                    ['name' => 'accent-emerald-700', 'hex_value' => '#047857'],
                    ['name' => 'accent-emerald-800', 'hex_value' => '#065f46'],
                    ['name' => 'accent-emerald-900', 'hex_value' => '#064e3b'],
                    ['name' => 'accent-emerald-950', 'hex_value' => '#022c22'],
                    // Добавляем остальные акцентные цвета
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
            ]);
        }
    }
}
