<?php
declare(strict_types=1);

namespace Smetaniny\TailwindcssConfig\seeders;

use Illuminate\Support\Facades\DB;
use Smetaniny\TailwindcssConfig\Commands\Contracts\SeederInterface;

/**
 * Сидер для заполнения таблицы `tw_accent_colors` всеми возможными акцентными цветами.
 *
 * @author Smetanin Sergey
 */
class TwAccentColorsSeed implements SeederInterface
{
    /**
     * Выполняет вставку данных в таблицу акцентных цветов.
     */
    public function run(): void
    {
        // Проверяем, что таблица пуста
        if (DB::table('tw_accent_colors')->count() == 0) {
            DB::table('tw_accent_colors')->insert([
                ['name' => 'accent-inherit', 'hex_value' => 'inherit', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-current', 'hex_value' => 'currentColor', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-transparent', 'hex_value' => 'transparent', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-black', 'hex_value' => '#000', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-white', 'hex_value' => '#fff', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-slate-50', 'hex_value' => '#f8fafc', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-slate-100', 'hex_value' => '#f1f5f9', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-slate-200', 'hex_value' => '#e2e8f0', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-slate-300', 'hex_value' => '#cbd5e1', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-slate-400', 'hex_value' => '#94a3b8', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-slate-500', 'hex_value' => '#64748b', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-slate-600', 'hex_value' => '#475569', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-slate-700', 'hex_value' => '#334155', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-slate-800', 'hex_value' => '#1e293b', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-slate-900', 'hex_value' => '#0f172a', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-slate-950', 'hex_value' => '#020617', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-gray-50', 'hex_value' => '#f9fafb', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-gray-100', 'hex_value' => '#f3f4f6', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-gray-200', 'hex_value' => '#e5e7eb', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-gray-300', 'hex_value' => '#d1d5db', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-gray-400', 'hex_value' => '#9ca3af', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-gray-500', 'hex_value' => '#6b7280', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-gray-600', 'hex_value' => '#4b5563', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-gray-700', 'hex_value' => '#374151', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-gray-800', 'hex_value' => '#1f2937', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-gray-900', 'hex_value' => '#111827', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-gray-950', 'hex_value' => '#030712', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-zinc-50', 'hex_value' => '#fafafa', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-zinc-100', 'hex_value' => '#f4f4f5', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-zinc-200', 'hex_value' => '#e4e4e7', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-zinc-300', 'hex_value' => '#d4d4d8', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-zinc-400', 'hex_value' => '#a1a1aa', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-zinc-500', 'hex_value' => '#71717a', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-zinc-600', 'hex_value' => '#52525b', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-zinc-700', 'hex_value' => '#3f3f46', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-zinc-800', 'hex_value' => '#27272a', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-zinc-900', 'hex_value' => '#18181b', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-zinc-950', 'hex_value' => '#09090b', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-neutral-50', 'hex_value' => '#fafafa', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-neutral-100', 'hex_value' => '#f5f5f5', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-neutral-200', 'hex_value' => '#e5e5e5', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-neutral-300', 'hex_value' => '#d4d4d4', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-neutral-400', 'hex_value' => '#a1a1a1', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-neutral-500', 'hex_value' => '#737373', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-neutral-600', 'hex_value' => '#525252', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-neutral-700', 'hex_value' => '#404040', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-neutral-800', 'hex_value' => '#262626', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-neutral-900', 'hex_value' => '#171717', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-neutral-950', 'hex_value' => '#0b0b0b', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-red-50', 'hex_value' => '#fef2f2', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-red-100', 'hex_value' => '#fee2e2', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-red-200', 'hex_value' => '#fecaca', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-red-300', 'hex_value' => '#fca5a1', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-red-400', 'hex_value' => '#f87171', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-red-500', 'hex_value' => '#ef4444', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-red-600', 'hex_value' => '#dc2626', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-red-700', 'hex_value' => '#b91c1c', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-red-800', 'hex_value' => '#991b1b', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-red-900', 'hex_value' => '#7f1d1d', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-red-950', 'hex_value' => '#450a0a', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-orange-50', 'hex_value' => '#fff7ed', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-orange-100', 'hex_value' => '#ffedd5', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-orange-200', 'hex_value' => '#ffd9b5', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-orange-300', 'hex_value' => '#ffb24d', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-orange-400', 'hex_value' => '#fb923c', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-orange-500', 'hex_value' => '#f97316', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-orange-600', 'hex_value' => '#ea580c', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-orange-700', 'hex_value' => '#c2410c', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-orange-800', 'hex_value' => '#9a3412', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-orange-900', 'hex_value' => '#7c2d12', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-orange-950', 'hex_value' => '#431407', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-amber-50', 'hex_value' => '#fffbeb', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-amber-100', 'hex_value' => '#fef3c7', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-amber-200', 'hex_value' => '#fde68a', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-amber-300', 'hex_value' => '#fcd34d', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-amber-400', 'hex_value' => '#fbbf24', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-amber-500', 'hex_value' => '#f59e0b', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-amber-600', 'hex_value' => '#d97706', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-amber-700', 'hex_value' => '#b45309', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-amber-800', 'hex_value' => '#92400e', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-amber-900', 'hex_value' => '#78350f', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-amber-950', 'hex_value' => '#451a0a', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-yellow-50', 'hex_value' => '#fefce8', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-yellow-100', 'hex_value' => '#fef9c3', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-yellow-200', 'hex_value' => '#fef08a', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-yellow-300', 'hex_value' => '#fcd34d', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-yellow-400', 'hex_value' => '#fbbf24', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-yellow-500', 'hex_value' => '#f59e0b', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-yellow-600', 'hex_value' => '#d97706', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-yellow-700', 'hex_value' => '#b45309', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-yellow-800', 'hex_value' => '#92400e', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-yellow-900', 'hex_value' => '#78350f', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-yellow-950', 'hex_value' => '#451a0a', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-green-50', 'hex_value' => '#f0fdf4', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-green-100', 'hex_value' => '#ccfbf1', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-green-200', 'hex_value' => '#99f6e4', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-green-300', 'hex_value' => '#5eead4', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-green-400', 'hex_value' => '#34d399', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-green-500', 'hex_value' => '#10b981', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-green-600', 'hex_value' => '#059669', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-green-700', 'hex_value' => '#047857', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-green-800', 'hex_value' => '#065f46', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-green-900', 'hex_value' => '#064e3b', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-green-950', 'hex_value' => '#022c22', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-teal-50', 'hex_value' => '#f0fdfa', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-teal-100', 'hex_value' => '#ccfbf1', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-teal-200', 'hex_value' => '#99f6e4', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-teal-300', 'hex_value' => '#5eead4', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-teal-400', 'hex_value' => '#34d399', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-teal-500', 'hex_value' => '#10b981', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-teal-600', 'hex_value' => '#059669', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-teal-700', 'hex_value' => '#047857', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-teal-800', 'hex_value' => '#065f46', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-teal-900', 'hex_value' => '#064e3b', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-teal-950', 'hex_value' => '#022c22', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-blue-50', 'hex_value' => '#eff6ff', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-blue-100', 'hex_value' => '#dbeafe', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-blue-200', 'hex_value' => '#bfdbfe', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-blue-300', 'hex_value' => '#93c5fd', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-blue-400', 'hex_value' => '#60a5fa', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-blue-500', 'hex_value' => '#3b82f6', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-blue-600', 'hex_value' => '#2563eb', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-blue-700', 'hex_value' => '#1d4ed8', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-blue-800', 'hex_value' => '#1e40af', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-blue-900', 'hex_value' => '#1e3a8a', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-blue-950', 'hex_value' => '#0f172a', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-indigo-50', 'hex_value' => '#eef2ff', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-indigo-100', 'hex_value' => '#e0e7ff', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-indigo-200', 'hex_value' => '#c7d2fe', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-indigo-300', 'hex_value' => '#a5b4fc', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-indigo-400', 'hex_value' => '#818cf8', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-indigo-500', 'hex_value' => '#6366f1', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-indigo-600', 'hex_value' => '#4f46e5', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-indigo-700', 'hex_value' => '#4338ca', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-indigo-800', 'hex_value' => '#3730a3', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-indigo-900', 'hex_value' => '#1e1a78', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-indigo-950', 'hex_value' => '#0f172a', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-violet-50', 'hex_value' => '#f5f3ff', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-violet-100', 'hex_value' => '#ede9fe', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-violet-200', 'hex_value' => '#e0c1fe', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-violet-300', 'hex_value' => '#d8b4fe', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-violet-400', 'hex_value' => '#c084f5', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-violet-500', 'hex_value' => '#a855f7', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-violet-600', 'hex_value' => '#9333ea', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-violet-700', 'hex_value' => '#7e22ce', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-violet-800', 'hex_value' => '#6b21a8', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-violet-900', 'hex_value' => '#581c87', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-violet-950', 'hex_value' => '#3b0f5c', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-purple-50', 'hex_value' => '#f5f0ff', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-purple-100', 'hex_value' => '#e8def8', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-purple-200', 'hex_value' => '#d8b4f8', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-purple-300', 'hex_value' => '#c084f5', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-purple-400', 'hex_value' => '#a855f7', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-purple-500', 'hex_value' => '#9333ea', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-purple-600', 'hex_value' => '#7e22ce', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-purple-700', 'hex_value' => '#6b21a8', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-purple-800', 'hex_value' => '#581c87', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-purple-900', 'hex_value' => '#4c1d95', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-purple-950', 'hex_value' => '#3b0f5c', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-fuchsia-50', 'hex_value' => '#fdf4ff', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-fuchsia-100', 'hex_value' => '#fae8ff', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-fuchsia-200', 'hex_value' => '#f5a3ff', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-fuchsia-300', 'hex_value' => '#e879f9', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-fuchsia-400', 'hex_value' => '#d946ef', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-fuchsia-500', 'hex_value' => '#c026d3', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-fuchsia-600', 'hex_value' => '#a21caf', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-fuchsia-700', 'hex_value' => '#9d174d', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-fuchsia-800', 'hex_value' => '#831843', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-fuchsia-900', 'hex_value' => '#701a75', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-fuchsia-950', 'hex_value' => '#4b092b', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-pink-50', 'hex_value' => '#fdf2f8', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-pink-100', 'hex_value' => '#fce7f3', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-pink-200', 'hex_value' => '#fbcfe8', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-pink-300', 'hex_value' => '#f9a8d4', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-pink-400', 'hex_value' => '#f472b6', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-pink-500', 'hex_value' => '#ec4899', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-pink-600', 'hex_value' => '#db2777', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-pink-700', 'hex_value' => '#be185d', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-pink-800', 'hex_value' => '#9f1239', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-pink-900', 'hex_value' => '#831843', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-pink-950', 'hex_value' => '#4b092b', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-rose-50', 'hex_value' => '#fff1f2', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-rose-100', 'hex_value' => '#ffe4e6', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-rose-200', 'hex_value' => '#fecdd3', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-rose-300', 'hex_value' => '#fda4af', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-rose-400', 'hex_value' => '#fb7185', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-rose-500', 'hex_value' => '#f43f5e', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-rose-600', 'hex_value' => '#e11d48', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-rose-700', 'hex_value' => '#be123c', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-rose-800', 'hex_value' => '#9f1239', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-rose-900', 'hex_value' => '#881337', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
                ['name' => 'accent-rose-950', 'hex_value' => '#4c1d95', 'theme_id' => 1,  'created_at' => now(), 'updated_at' => now()],
            ]);
        }
    }
}
